apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: microservice-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: microservice-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: microservice-voting-app
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80    